### ISSUE TITLE
Risk that Todo IDs won't be unique 

### ISSUE THREAD

**Issue by neilmispelaar** [irm1005-itec1005-fall-2023/assignment-03-RaymondToyosato#2]
The risk with using `.length` is that you may create multiple todos with the same ID (depending on if a user deletes a bunch and then adds a bunch and deletes a bunch). 

Much better to use a counter that increments every time a todo is added to the array. 

https://github.com/irm1005-itec1005-fall-2023/assignment-03-RaymondToyosato/blob/0d292d597b37e92028762fca657fab308c4e22c8/script.js#L64

**Comment by RaymondToyosato** [comment]
Problem fixed.
